protected/models/Ail.php
<?php

/**
 * This is the model class for table "ail".
 *
 * The followings are the available columns in table 'ail':
 * @property integer $id_ail
 * @property string $tanggal_buat
 * @property string $tanggal_update
 * @property integer $petugas_id
 * @property integer $pelanggan_id
 * @property string $kode_rak
 * @property string $kode_map
 * @property integer $rayon_id
 * @property integer $lemari_id
 * @property integer $rak_id
 * @property integer $kolom_id
 * @property integer $baris_id
 * @property integer $kondisi_amplop
 * @property integer $kondisi_ail
 * @property integer $surat_surat_permohonan
 * @property integer $surat_identitas_pelanggan
 * @property integer $surat_data_survei
 * @property integer $surat_jawaban
 * @property integer $surat_perjanjian
 * @property integer $surat_pernyataan
 * @property integer $surat_kuitansi
 * @property integer $surat_perintah_kerja
 * @property integer $surat_bap
 * @property integer $surat_pdl
 * @property integer $surat_lainlain
 * @property string $deskripsi
 * @property integer $status
 */
class Ail extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'ail';
	}

	public $file, $searchKode, $searchNama;

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			// array('tanggal_buat, tanggal_update, petugas_id, pelanggan_id, kode_rak, rayon_id, lemari_id, rak_id, kolom_id, baris_id, kondisi_amplop, kondisi_ail, surat_surat_permohonan, surat_identitas_pelanggan, surat_data_survei, surat_jawaban, surat_perjanjian, surat_pernyataan, surat_kuitansi, surat_perintah_kerja, surat_bap, surat_pdl, surat_lainlain', 'required'),
			array('tanggal_buat, tanggal_update, petugas_id, pelanggan_id, kode_rak, rayon_id, lemari_id, rak_id, kolom_id, baris_id', 'required'),
			array('petugas_id, pelanggan_id, rayon_id, lemari_id, kolom_id, baris_id, kondisi_amplop, kondisi_ail, surat_surat_permohonan, surat_identitas_pelanggan, surat_data_survei, surat_jawaban, surat_perjanjian, surat_pernyataan, surat_kuitansi, surat_perintah_kerja, surat_bap, surat_pdl, surat_lainlain, status, nomor_urut', 'numerical', 'integerOnly'=>true),
			array('kode_rak, kode_map', 'length', 'max'=>25),
			array('deskripsi', 'length', 'max'=>255),
			array('deskripsi', 'safe'),
			array('pelanggan_id', 'unique'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id_ail, tanggal_buat, tanggal_update, petugas_id, pelanggan_id, kode_rak, rayon_id, lemari_id, rak_id, kolom_id, baris_id, kondisi_amplop, kondisi_ail, surat_surat_permohonan, surat_identitas_pelanggan, surat_data_survei, surat_jawaban, surat_perjanjian, surat_pernyataan, surat_kuitansi, surat_perintah_kerja, surat_bap, surat_pdl, surat_lainlain, deskripsi, status', 'safe', 'on'=>'search'),
			array('searchKode', 'safe'),
			array('searchNama', 'safe'),
			);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'Pelanggan'=>array(self::BELONGS_TO,'Pelanggan','pelanggan_id'),
			'Petugas'=>array(self::BELONGS_TO,'Petugas','petugas_id'),
			);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id_ail' => 'Id Ail',
			'tanggal_buat' => 'Tanggal Buat',
			'tanggal_update' => 'Tanggal Update',
			'petugas_id' => 'Petugas',
			'pelanggan_id' => 'Pelanggan',
			'kode_rak' => 'Kode Rak',
			'rayon_id' => 'Rayon',
			'lemari_id' => 'Lemari',
			'rak_id' => 'Rak',
			'kolom_id' => 'Kolom',
			'baris_id' => 'Baris',
			'kondisi_amplop' => 'Kondisi Amplop',
			'kondisi_ail' => 'Kondisi Ail',
			'surat_surat_permohonan' => 'Surat Surat Permohonan',
			'surat_identitas_pelanggan' => 'Surat Identitas Pelanggan',
			'surat_data_survei' => 'Surat Data Survei',
			'surat_jawaban' => 'Surat Jawaban',
			'surat_perjanjian' => 'Surat Perjanjian',
			'surat_pernyataan' => 'Surat Pernyataan',
			'surat_kuitansi' => 'Surat Kuitansi',
			'surat_perintah_kerja' => 'Surat Perintah Kerja',
			'surat_bap' => 'Surat BA',
			'surat_pdl' => 'Surat SLO',
			'surat_lainlain' => 'Surat Lainlain',
			'deskripsi' => 'Keterangan',
			'status' => 'Status',
			);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_ail',$this->id_ail);
		$criteria->compare('tanggal_buat',$this->tanggal_buat,true);
		$criteria->compare('tanggal_update',$this->tanggal_update,true);
		$criteria->compare('petugas_id',$this->petugas_id);
		$criteria->compare('pelanggan_id',$this->pelanggan_id);
		$criteria->compare('kode_rak',$this->kode_rak,true);
		$criteria->compare('rayon_id',$this->rayon_id);
		$criteria->compare('lemari_id',$this->lemari_id);
		$criteria->compare('rak_id',$this->rak_id);
		$criteria->compare('kolom_id',$this->kolom_id);
		$criteria->compare('baris_id',$this->baris_id);
		$criteria->compare('kondisi_amplop',$this->kondisi_amplop);
		$criteria->compare('kondisi_ail',$this->kondisi_ail);
		$criteria->compare('surat_surat_permohonan',$this->surat_surat_permohonan);
		$criteria->compare('surat_identitas_pelanggan',$this->surat_identitas_pelanggan);
		$criteria->compare('surat_data_survei',$this->surat_data_survei);
		$criteria->compare('surat_jawaban',$this->surat_jawaban);
		$criteria->compare('surat_perjanjian',$this->surat_perjanjian);
		$criteria->compare('surat_pernyataan',$this->surat_pernyataan);
		$criteria->compare('surat_kuitansi',$this->surat_kuitansi);
		$criteria->compare('surat_perintah_kerja',$this->surat_perintah_kerja);
		$criteria->compare('surat_bap',$this->surat_bap);
		$criteria->compare('surat_pdl',$this->surat_pdl);
		$criteria->compare('surat_lainlain',$this->surat_lainlain);
		$criteria->compare('deskripsi',$this->deskripsi,true);
		$criteria->compare('status',$this->status);
		$criteria->order = 'id_ail DESC';

		$criteria->with = array('Pelanggan',);
		$criteria->addSearchCondition('Pelanggan.kode', $this->searchKode);
		$criteria->addSearchCondition('Pelanggan.name', $this->searchNama);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Ail the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function countFile($data,$id){
		if($data==1){
			return FilePermohonan::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==2){
			return FilePelanggan::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==3){
			return FileSurvei::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==4){
			return FileJawaban::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==5){
			return FilePerjanjian::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==6){
			return FilePernyataan::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==7){
			return FileKuitansi::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==8){
			return FilePerintahKerja::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==9){
			return FileBap::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==10){
			return FilePdl::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==11){
			return FileLain::model()->countByAttributes(array('ail_id'=>$id));
		}elseif($data==12){
			return "-";
		}
	}

	public function status($data){
		if($data==1){
			return "Ada";
		}else{
			return "Tidak Ada";
		}
	}

	public function fileData($data){
		if($data==1){
			return "FilePermohonan";
		}elseif($data==2){
			return "FilePelanggan";
		}elseif($data==3){
			return "FileSurvei";
		}elseif($data==4){
			return "FileJawaban";
		}elseif($data==5){
			return "FilePerjanjian";
		}elseif($data==6){
			return "FilePernyataan";
		}elseif($data==7){
			return "FileKuitansi";
		}elseif($data==8){
			return "FilePerintahKerja";
		}elseif($data==9){
			return "FileBap";
		}elseif($data==10){
			return "FilePdl";
		}elseif($data==11){
			return "FileLain";
		}elseif($data==12){
			return "-";
		}
	}

	public function titleData($data){
		if($data==1){
			return "Surat Permohonan";
		}elseif($data==2){
			return "Surat Identitas Pelanggan";
		}elseif($data==3){
			return "Surat Data Survei";
		}elseif($data==4){
			return "Surat Jawaban";
		}elseif($data==5){
			return "Surat Perjanjian";
		}elseif($data==6){
			return "Surat Pernyataan";
		}elseif($data==7){
			return "Surat Kuitansi";
		}elseif($data==8){
			return "Surat Perintah Kerja";
		}elseif($data==9){
			return "Surat BA";
		}elseif($data==10){
			return "Surat SLO";
		}elseif($data==11){
			return "Surat Lain-lain";
		}elseif($data==12){
			return "-";
		}
	}

	public function direktoriFile($data){
		if($data==1){
			return "surat-permohonan";
		}elseif($data==2){
			return "surat-pelanggan";
		}elseif($data==3){

protected/controllers/AilController.php
<?php

class AilController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			// 'postOnly + delete', // we only allow deletion via POST request
			);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions'=>array('create','update','view','delete','admin','printkodemap','printverifikasi'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->record->level==4',
				),		
			array('allow',
				'actions'=>array('create','update','view','delete','admin','printkodemap','printverifikasi'),
				'users'=>array('@'),
				'expression'=>'Yii::app()->user->record->level==1',
				),
			array('deny',
				'users'=>array('*'),
				),
			);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
			));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate($lemari,$rak,$kolom,$baris,$rak_id)
	{
		$model=new Ail;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Ail']))
		{
			$model->attributes=$_POST['Ail'];
			$model->tanggal_buat = date('Y-m-d h:i:s');
			$model->tanggal_update = date('Y-m-d h:i:s');
			$model->petugas_id = YII::app()->user->id;
			$model->kode_rak = $rak;
			$model->lemari_id = $lemari;
			$model->rak_id = $rak;
			$model->kolom_id = $kolom;
			$model->baris_id = $baris;
			$model->status = 1;
			if($model->save()){
				$this->redirect(array('view','id'=>$model->id_ail));
			}
		}

		$this->render('create',array(
			'model'=>$model,
			'lemari'=>$lemari,
			'rak'=>$rak,
			'kolom'=>$kolom,
			'baris'=>$baris,
			'rak_id'=>$rak_id,
			));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Ail']))
		{
			$model->attributes=$_POST['Ail'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_ail));
		}

		$this->render('update',array(
			'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Ail');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
			));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Ail('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Ail']))
			$model->attributes=$_GET['Ail'];

		$this->render('admin',array(
			'model'=>$model,
			));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Ail the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Ail::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Ail $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='ail-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionPrintKodeMap($id)
	{
		$this->layout = "print";
		$this->render('print',array(
			'model'=>$this->loadModel($id),
			));
	}	

	public function actionPrintVerifikasi($id)
	{
		$this->layout = "print";
		$this->render('print_verifikasi',array(
			'model'=>$this->loadModel($id),
			));
	}		
}

protected/views/ail/_search.php
<?php
/* @var $this AilController */
/* @var $model Ail */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id_ail'); ?>
		<?php echo $form->textField($model,'id_ail'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tanggal_buat'); ?>
		<?php echo $form->textField($model,'tanggal_buat'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tanggal_update'); ?>
		<?php echo $form->textField($model,'tanggal_update'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'petugas_id'); ?>
		<?php echo $form->textField($model,'petugas_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'pelanggan_id'); ?>
		<?php echo $form->textField($model,'pelanggan_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'kode_rak'); ?>
		<?php echo $form->textField($model,'kode_rak',array('size'=>25,'maxlength'=>25)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'rayon_id'); ?>
		<?php echo $form->textField($model,'rayon_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'lemari_id'); ?>
		<?php echo $form->textField($model,'lemari_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'rak_id'); ?>
		<?php echo $form->textField($model,'rak_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'kondisi_amplop'); ?>
		<?php echo $form->textField($model,'kondisi_amplop'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'kondisi_ail'); ?>
		<?php echo $form->textField($model,'kondisi_ail'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_surat_permohonan'); ?>
		<?php echo $form->textField($model,'surat_surat_permohonan'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_identitas_pelanggan'); ?>
		<?php echo $form->textField($model,'surat_identitas_pelanggan'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_data_survei'); ?>
		<?php echo $form->textField($model,'surat_data_survei'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_jawaban'); ?>
		<?php echo $form->textField($model,'surat_jawaban'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_perjanjian'); ?>
		<?php echo $form->textField($model,'surat_perjanjian'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_pernyataan'); ?>
		<?php echo $form->textField($model,'surat_pernyataan'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_kuitansi'); ?>
		<?php echo $form->textField($model,'surat_kuitansi'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_perintah_kerja'); ?>
		<?php echo $form->textField($model,'surat_perintah_kerja'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_bap'); ?>
		<?php echo $form->textField($model,'surat_bap'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_pdl'); ?>
		<?php echo $form->textField($model,'surat_pdl'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'surat_lainlain'); ?>
		<?php echo $form->textField($model,'surat_lainlain'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'deskripsi'); ?>
		<?php echo $form->textArea($model,'deskripsi',array('rows'=>6, 'cols'=>50)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'status'); ?>
		<?php echo $form->textField($model,'status'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/ail/_view_file.php
<?php
/* @var $this FileAilController */
/* @var $data FileAil */
?>

<div class="col-xs-12 col-md-6 col-lg-6">
	<!-- Default box -->
	<div class="box box-solid">
		<div class="box-header">
			<h4 class="box-title">

				<?php echo CHtml::link(CHtml::encode("Download #". $data->file), array('view', 'id'=>$data->id)); ?>
			</h4>
		</div>
		<div class="box-body">

			<?php $this->widget('zii.widgets.CDetailView', array(
				'data'=>$data,
				'htmlOptions'=>array("class"=>"table"),
				'attributes'=>array(
					'tanggal_buat',
					'tanggal_update',
					'deskripsi',
					),
					)); ?>

				</div><!-- /.box-body -->
			</div><!-- /.box -->
		</div>

protected/views/ail/_view_tab.php
<div id="exTab1">	
	<ul  class="nav nav-pills">
		<?php for ($i = 1; $i <= 11; $i++) { 
			$eh = Ail::model()->titleData($i);
			$ya = Ail::model()->countFile($i,$model->id_ail);
			if($ya!=0):
				?>

			<li><a href="#<?php echo $i; ?>a" data-toggle="tab"><?php echo $eh; ?></a></li>

			<?php
			endif;
		} 
		?>
	</ul>

	<div class="tab-content clearfix">

		<?php for ($i = 1; $i <= 11; $i++) { ?>

			<div class="tab-pane" id="<?php echo $i; ?>a">
				<HR>
					<?php 
					$ini = Ail::model()->fileData($i);
					$itu = Ail::model()->titleData($i);
					$nah = Ail::model()->direktoriFile($i);
					echo "<div class='alert alert-warning'>";
					echo "<h4><i class='fa fa-file-text'></i> ".$itu."</h4>";
					echo "</div>";
					$dataProvider=new CActiveDataProvider($ini,
						array('criteria'=>array(
							'condition'=>'status=1 AND ail_id='.$model->id_ail)
						));

					echo "<div class='row'>";
					foreach($dataProvider->getData() as $data){

						echo "<div class='col-sm-6 col-lg-6'>";
						echo "<div class='widget-simple-chart text-right card-box'>";
						echo "<h3 class='text-success counter'><a href='".YII::app()->baseUrl."/file/".$nah."/".$data->file."'>Download File</a></h3>";
						echo "<p class='text-muted'>Tanggal Upload : ".$data->tanggal_buat." </BR>Tanggal Update : ".$data->tanggal_update."</p>";
						echo "</div>";
						echo "</div>";

					}
					echo "</div>";
					?>

				</div>

				<?php } ?>

			</div>
		</div>

protected/views/ail/admin.php
<?php
/* @var $this AilController */
/* @var $model Ail */

$this->breadcrumbs=array(
	'Ails'=>array('index'),
	'Kelola',
	);

$this->pageTitle='Kelola Ail';
?>



<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'ail-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'itemsCssClass' => 'table table-bordered table-striped dataTable table-hover',
	'columns'=>array(

		array(
			'header'=>'No',
			'value'=>'$this->grid->dataProvider->pagination->currentPage*$this->grid->dataProvider->pagination->pageSize + $row+1',
			'htmlOptions'=>array('width'=>'10px', 
				'style' => 'text-align: center;')),

					// 'id_ail',
		'tanggal_buat',
		'kode_map',
		// array('name'=>'petugas_id','value'=>'$data->Petugas->nama'),
		array('name'=>'pelanggan_id','value'=>'$data->Pelanggan->kode','filter' => CHtml::activeTextField($model, 'searchKode'),),

					// 'tanggal_update',
		/*
		'rayon_id',
		'lemari_id',
		'rak_id',
		'kondisi_amplop',
		'kondisi_ail',
		'surat_surat_permohonan',
		'surat_identitas_pelanggan',
		'surat_data_survei',
		'surat_jawaban',
		'surat_perjanjian',
		'surat_pernyataan',
		'surat_kuitansi',
		'surat_perintah_kerja',
		'surat_bap',
		'surat_pdl',
		'surat_lainlain',
		'deskripsi',
		'status',
		*/

		array(
			'class'=>'CButtonColumn',
			'template'=>'{update}',
			'header'=>'Edit AIL',
			'buttons'=>array(
					//Button Print
				'update'=>
				array(
					'label'=>'Edit',
					'url'=>'Yii::app()->createUrl("ail/update", array("id"=>$data->id_ail))',
					'imageUrl'=>Yii::app()->request->baseUrl.'/images/edit.png',
					),


				),
			),

		array(
			'class'=>'CButtonColumn',
			'template'=>'{report}',
			'header'=>'Print Map',
			'buttons'=>array(
					//Button Print
				'report'=>
				array(
					'label'=>'Print Map',
					'url'=>'Yii::app()->createUrl("ail/printkodemap", array("id"=>$data->id_ail))',
					'imageUrl'=>Yii::app()->request->baseUrl.'/images/print.png',
					),


				),
			),

		array(
			'class'=>'CButtonColumn',
			'template'=>'{report}',
			'header'=>'Print Verifikasi',
			'buttons'=>array(
					//Button Print
				'report'=>
				array(
					'label'=>'Print Verifikasi',
					'url'=>'Yii::app()->createUrl("ail/printverifikasi", array("id"=>$data->id_ail))',
					'imageUrl'=>Yii::app()->request->baseUrl.'/images/print.png',
					),


				),
			),		

		array(
			'header'=>'Action',
			'template'=>'{view}{delete}',
			'class'=>'CButtonColumn',
			'htmlOptions'=>array('width'=>'100px', 
				'style' => 'text-align: center;'),
			),
		),
		)); ?>


<?php echo CHtml::link('Registrasi AIL',
	array('site/registrasi'),
	array('class' => 'btn btn-warning pull-left btn-flat'));
	?>

	<BR>
		<BR>

protected/views/ail/create.php
<?php
/* @var $this AilController */
/* @var $model Ail */

$this->breadcrumbs=array(
	'Ails'=>array('index'),
	'Tambah',
	);

$this->pageTitle='Tambah Ail';
?>

<?php echo $this->renderPartial('_form', array(
	'model'=>$model,	
	'lemari'=>$lemari,
	'rak'=>$rak,
	'kolom'=>$kolom,
	'baris'=>$baris,
	'rak_id'=>$rak_id
	)); ?>

protected/views/ail/update.php
<?php
/* @var $this AilController */
/* @var $model Ail */

$this->breadcrumbs=array(
	'Ails'=>array('index'),
	$model->id_ail=>array('view','id'=>$model->id_ail),
	'Update',
	);

$this->pageTitle='Edit Ail';
?>

<?php echo $this->renderPartial('_form_update', array('model'=>$model)); ?>